packages:
  - "."

overrides:
  "cross-spawn": ">=7.0.6"
  "minimatch": ">=10.2.5"
  "glob": ">=13.0.6"
  "brace-expansion": ">=5.0.6"
  "array-includes": "npm:@nolyfill/array-includes@latest"
  "array.prototype.findlastindex": "npm:@nolyfill/array.prototype.findlastindex@latest"
  "array.prototype.flat": "npm:@nolyfill/array.prototype.flat@latest"
  "array.prototype.flatmap": "npm:@nolyfill/array.prototype.flatmap@latest"
  "array.prototype.tosorted": "npm:@nolyfill/array.prototype.tosorted@latest"
  "es-iterator-helpers": "npm:@nolyfill/es-iterator-helpers@latest"
  "has": "npm:@nolyfill/has@latest"
  "object.assign": "npm:@nolyfill/object.assign@latest"
  "object.entries": "npm:@nolyfill/object.entries@latest"
  "object.fromentries": "npm:@nolyfill/object.fromentries@latest"
  "object.groupby": "npm:@nolyfill/object.groupby@latest"
  "object.hasown": "npm:@nolyfill/object.hasown@latest"
  "object.values": "npm:@nolyfill/object.values@latest"
  "string.prototype.matchall": "npm:@nolyfill/string.prototype.matchall@latest"
  "flatted": ">=3.4.2"
  "picomatch@2": ">=4.0.4"
  "picomatch@4": ">=4.0.4"
  "yaml": ">=2.9.0"

# 请确保底部的这一块被正确修改为 true
allowBuilds:
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - ws@7.5.11
  - js-yaml@4.1.2
  - '@babel/core@7.29.1'
